### ISSUE TITLE
TCP Router egress from AWS on Reference Architecture

### ISSUE THREAD

**Issue by skibum55** [pivotal-cf/docs-pcf-refarch#2]
We need to illustrate an exit point for any apps bound to the TCP Routers in the AWS reference architecture.  Looks like GCP & Azure have a single entry point already.  We should consider whether this needs to be a 1..n option on the AWS doc.  Happy to help as needed.

**Comment by animatedmax** [comment]
Hi @skibum55 We updated http://docs.pivotal.io/pivotalcf/1-9/refarch/aws/aws_ref_arch.html and http://docs.pivotal.io/pivotalcf/1-10/refarch/aws/aws_ref_arch.html with the information you provided. Thanks!
