### ISSUE TITLE
AWS ref architecture document

### ISSUE THREAD

**Issue by phopper-pivotal** [pivotal-cf/docs-pcf-refarch#23]
possible to get the OmniGraffle file used to generate the AWS ref architecture document

**Comment by animatedmax** [comment]
Hi @phopper-pivotal The files are in this repository, in the following folder: images/PCF-AWS-RefArch-Overview.graffle/

**Comment by animatedmax** [comment]
Oops, sorry, hit the wrong button.

Please let us know if you cannot access the files. Thanks!

**Comment by phopper-pivotal** [comment]
i've got access to the graffle. this can be closed. thank you.
