### ISSUE TITLE
Issues with Alternative GCP Network Layouts for PCF

### ISSUE THREAD

**Issue by abbyachau** [pivotal-cf/docs-pcf-refarch#25]
Ref arch says that the main install docs for GCP uses the "Every PCF VM receives its own public IP address" approach however it looks like the docs uses the NATS approach:

https://docs.pivotal.io/pivotalcf/2-0/customizing/gcp-prepare-env.html

**Comment by ljarzynski** [comment]
Thanks for pointing this out @abbyachau. I updated this doc to correctly say that the GCP instrux use NAT. In the 2.0 version, I also point out that the Terraform templates use the VM Public IP method.
