### ISSUE TITLE
CIDRs on the diagram do not match the CIDRs called out in the text

### ISSUE THREAD

**Issue by tcrockett1138** [pivotal-cf/docs-pcf-refarch#36]
The CIDRs on the [openstack-overview-arch](https://raw.githubusercontent.com/pivotal-cf/docs-pcf-refarch/1.10/images/openstack-overview-arch.png) diagram are as follows.
```
Infrastructure /26
ERT /22
Services /22
On-Demand Services /22
```

In the [OpenStack Objects](https://docs.pivotal.io/pivotalcf/1-12/refarch/openstack/openstack_ref_arch.html#openstack_components) section, the text calls out the following.
```
Infrastructure /24
ERT /20
Services /20
On-Demand Services /24
```

It looks like there are updates to the diagrams in this [pull request](https://github.com/pivotal-cf/docs-pcf-refarch/pull/35) but I'm unable to see if these changes have already been made to the images.

**Comment by seviet** [comment]
hey @tcrockett1138 -- the PR removed the On-Demand Services network, but the inconsistency is still there. let me try to find out which one is accurate.

**Comment by mlimonczenko** [comment]
Hello @tcrockett1138,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
