### ISSUE TITLE
c0-ops repo has been moved

### ISSUE THREAD

**Issue by skibum55** [pivotal-cf/docs-pcf-refarch#4]
All links referring to c0-ops repo on github should instead refer to the new github.com/pivotal-cf/aws-concourse repo instead.

**Comment by bentarnoff** [comment]
Hey @skibum55 could you be more specific about the change you want to see here? I've just done a search through `docs-pcf-refarch` and I don't see any links to a `c0-ops` repo.

**Comment by ljarzynski** [comment]
@bentarnoff @skibum55 It's possible that I addressed this here: https://github.com/pivotal-cf/docs-pcf-refarch/commit/761d1f3ab1bec4b3e3248e29ce099e3f4156e46a (and the commit right before that)

**Comment by bentarnoff** [comment]
Ah, great. @skibum55 if @ljarzynski's changes satisfy your concerns, let me know and I'll close the issue.

**Comment by bentarnoff** [comment]
@skibum55 I'm closing this, but feel free to re-open or raise another issue if you have additional concerns. Thanks.
