### ISSUE TITLE
Azure ref arch

### ISSUE THREAD

**Issue by pakiheart** [pivotal-cf/docs-pcf-refarch#51]
https://raw.githubusercontent.com/pivotal-cf/docs-pcf-refarch/master/images/azure-multi-resgroup-multi-lb.png

Looking at the ALB, sys domain traffic goes to `ALB apps` and app traffic go through `ALB API`, labels seem backward on the image

**Comment by lsilvapvt** [comment]
Azure ref arch diagram updated to fix the reported typo. 
Thanks for reporting it @pakiheart  !

**Comment by lsilvapvt** [comment]
Commit 55de643872eefff1e2f1fb758516a90e8e3be65f

**Comment by lsilvapvt** [comment]
This update should be backported to the PCF docs all the way from 2.0 and forward.
