### ISSUE TITLE
2.7 Vsphere Reference Architecture formatting issue

### ISSUE THREAD

**Issue by patrick-huber-pivotal** [pivotal-cf/docs-pcf-refarch#63]
On the documentation page for vsphere reference architecture: https://docs.pivotal.io/platform/2-7/plan/vsphere/vsphere_ref_arch.html#pas-routed-networking

There appears to be a missing closing &lt;p&gt; tag which is causing the following sections to be added to the note section instead of being broken out into individual sections:

https://github.com/pivotal-cf/docs-pcf-refarch/blob/38d09eadb4de9fc845b091832a960feaa4d19382/vsphere/vsphere_ref_arch.html.md.erb#L287

You can see the formatting issue in the attached image:
![docs-pcf-refarch-vsphere-formatting](https://user-images.githubusercontent.com/37094097/70453577-ffe6cb80-1a76-11ea-9b09-81d8a826ad53.PNG)

**Comment by jellers** [comment]
I also have this issue.

**Comment by animatedmax** [comment]
Hi @patrick-huber-pivotal Thank you for pointing out this issue. We've removed the errors and the issue should now be resolved.
