### ISSUE TITLE
Migrating Pivotal Platform to a New Datastore in vSphere Doc Issues

### ISSUE THREAD

**Issue by timlharrison** [pivotal-cf/docs-pcf-refarch#66]
The Migrating Pivotal Platform to a New Datastore in vSphere doc (https://docs.pivotal.io/platform/2-8/plan/vsphere/vsphere_migrate_datastore.html) may have some issues:

- Step 2: Document Current Environment Settings says to "Note the datastore where each VM resides in vSphere" but the bosh instances --details command on 2.8 does not show the datastores.  It only shows the disk CIDs.  Unless you're telling customers to go manually document what datastore each PCF VM is on, you may want to clarify.

- Main Procedure section says, in step 7, to "Confirm that the BOSH Director VM has persistent disk on the new datastore" by "Locat[ing] the Ops Manager VM and verify that the VM has an expected value in the Provisioned Space column" which doesn't really confirm anything about the BOSH Director VM as it is a completely different VM from the Ops Manager VM.  The way I was able to verify that the BOSH Director VM had a persistent disk on the new datastore was by browsing to the VM in vSphere and looking at the attached disks' file locations.

**Comment by mlimonczenko** [comment]
Hello @timlharrison,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
