### ISSUE TITLE
Ref Arch Diagrams Should be updated with Tanzu branding

### ISSUE THREAD

**Issue by doddatpivotal** [pivotal-cf/docs-pcf-refarch#68]
The following page has diagrams that still reference Pivotal Cloud Foundry and PKS

https://github.com/pivotal-cf/docs-pcf-refarch/blob/2.10/vsphere/vsphere_ref_arch.html.md.erb

https://docs.pivotal.io/platform/2-10/plan/vsphere/vsphere_ref_arch.html#pks-nsx-t

**Comment by paigecalvert** [comment]
Thank you @doddatpivotal! This is on our radar and we're currently prioritizing this work against other necessary updates. I'm going to close out this issue, but feel free to re-open if you have additional questions!
