### ISSUE TITLE
Image and description mismatch for Network Design section

### ISSUE THREAD

**Issue by cxhercules** [pivotal-cf/docs-pcf-refarch#7]
Network Design Image below does not correspond with description. In particular it is missing IsoZone. 

```
On the tenant side, each interface defined on the NSX Edge acts as the IP gateway for the network used on that port group. Pivotal recommends allocating the following address ranges for the networks, and defining the gateway at .1 for each:

Infra (infrastructure) network: 192.168.10.0/26
Deployment network: 192.168.20.0/22
CF Tiles network: 192.168.24.0/22
Dynamic Services network: 192.168.28.0/22
IsoZone## network: 192.168.32.0/22, Gateway at .1
```
https://github.com/pivotal-cf/docs-pcf-refarch/blob/1.10/vsphere/vsphere_ref_arch.html.md.erb#L132

![](http://docs.pivotal.io/pivotalcf/1-10/refarch/images/vsphere-exploded-edge.png)

**Comment by bentarnoff** [comment]
Thanks for this @hhercules. @ryanpei can you speak to this?

**Comment by forddonald** [comment]
![pcf refarch vsphere nsx v4 nsx-exploded](https://user-images.githubusercontent.com/8728723/28131440-7a8699b6-66ff-11e7-828f-453260b273f5.png)

**Comment by bentarnoff** [comment]
Hey @cxhercules thanks for bringing this to our attention! You can find the correct diagram above, as provided by @forddonald. We are updating the docs accordingly, and the updated diagram will be live on our site soon. Thanks again.
